import w from './worker.js';
const kv = new Map();
const BOARD = { get: async (k, t) => { const v = kv.get(k); return v === undefined ? null : (t === 'json' ? JSON.parse(v) : v); }, put: async (k, v) => { kv.set(k, v); }, delete: async k => { kv.delete(k); }, list: async ({ prefix }) => ({ keys: [...kv.keys()].filter(k => k.startsWith(prefix)).map(name => ({ name })) }) };
const env = { BOARD, SYNC_KEY: 'sync-secret', OFFICER_CODE: 'off123', MEMBER_CODE: 'mem456' };
const call = (path, opt = {}) => w.fetch(new Request('https://x.test' + path, opt), env).then(async r => [r.status, await r.json().catch(() => null)]);
const data = JSON.stringify({ history: [], canyon: [{ name: 'Kathi' }, { name: 'BB' }], meta: {}, dates: [], rules: [] });
let fails = 0; const ok = (c, m) => { if (!c) { fails++; console.log('FAIL', m); } };
ok((await call('/data'))[0] === 404, 'no data yet');
ok((await call('/data', { method: 'POST', body: data }))[0] === 403, 'data needs sync key');
ok((await call('/data', { method: 'POST', body: data, headers: { 'X-Sync-Key': 'sync-secret' } }))[1].ok, 'data stored');
ok((await call('/data'))[1].canyon.length === 2, 'data served');
ok((await call('/whoami', { headers: { 'X-Code': 'mem456' } }))[1].role === 'member', 'member code');
ok((await call('/whoami', { headers: { 'X-Code': 'nope' } }))[0] === 401, 'bad code');
ok((await call('/edit', { method: 'POST', headers: { 'X-Code': 'mem456' }, body: JSON.stringify({ name: 'Kathi', avail: 'Both', by: 'Kathi' }) }))[1].ok, 'member avail');
ok((await call('/edit', { method: 'POST', headers: { 'X-Code': 'mem456' }, body: JSON.stringify({ name: 'Kathi', slot: 'T1 Sub' }) }))[0] === 403, 'member cannot slot');
ok((await call('/edit', { method: 'POST', headers: { 'X-Code': 'off123' }, body: JSON.stringify({ name: 'BB', slot: 'T1 Sub' }) }))[1].ok, 'officer slot');
ok((await call('/edit', { method: 'POST', headers: { 'X-Code': 'off123' }, body: JSON.stringify({ name: 'Ghost', avail: 'Both' }) }))[0] === 404, 'unknown member');
ok((await call('/edit', { method: 'POST', headers: { 'X-Code': 'off123' }, body: JSON.stringify({ name: 'BB', avail: 'lunch' }) }))[0] === 400, 'bad avail');
const [, pend] = await call('/edits', { headers: { 'X-Sync-Key': 'sync-secret' } });
ok(pend.edits.length === 2 && pend.edits[0].name === 'Kathi', 'pending list ' + JSON.stringify(pend));
ok((await call('/edits/ack', { method: 'POST', headers: { 'X-Sync-Key': 'sync-secret' }, body: JSON.stringify({ ids: pend.edits.map(e => e.id), failed: { [pend.edits[1].id]: 'bad slot' } }) }))[1].acked === 2, 'ack');
ok((await call('/edits', { headers: { 'X-Sync-Key': 'sync-secret' } }))[1].edits.length === 0, 'queue empty');
const [, log] = await call('/log'); ok(log.log.length === 2 && log.log[1].error === 'bad slot' && !('role' in log.log[0] && log.log[0].id), 'log ' + JSON.stringify(log));
ok((await call('/x', { method: 'OPTIONS' })).length === 2, 'options');
console.log(fails ? fails + ' FAILURES' : 'WORKER TESTS PASSED');
